server:
  port: 8080
spring:
  datasource:
    first:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3316/geektimedb?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
      username: root
      password: 123456
    second:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3326/geektimedb?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
      username: root
      password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    open-in-view: true